name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Linting
      - name: Run Linting
        run: npm run lint

      # Step 5: Build the project
      - name: Build the project
        run: npm run build
        with:
          publish_dir: ./dist

